apiVersion: apps/v1
kind: Deployment
metadata:
  name: phptest-deployment-jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phptest
  template:
    metadata:
      labels:
        app: phptest
    spec:
      containers:
      - name: phptest
        image: wallowitch2/phptest-jenkins:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbhost
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbuser
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbpasswd
